# Site settings
title: New developer
header-img: img/home-bg.png
email: onm210@nyu.edu
copyright_name: orianamansur
description: > # this means to ignore newlines until "baseurl:"
  journey into the world of coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  orianamansur
learn_profile: orianamansur
email_username: onm210@nyu.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
